version: '2'
services:
  apache:
    build: .
    volumes:
    - "./src/:/var/www/html"
    links:
    - db
    ports:
    - "80:80"
    privileged: true

  db:
    image: mysql:latest
    restart: always
    volumes:
    - "./data/:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_PASSWORD=toor
    ports:
    - "3306:3306"
    privileged: true

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - PMA_HOST=172.18.0.1
    links:
      - db
    restart: always
    privileged: true
    ports:
      - "9999:80"
